name: github actions to push container images to dockerhub when code is changed

on:
  push:
    branches:
      - main
    paths:
      - api/**

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      # This steps checks out a copy of the repository
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: $${{ vars.DOCKERHUB_USERNAME }}
          password: $${{ vars.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-fastapi:latest
